// export enum ENVEnum {
//     NODE_ENV = 'NODE_ENV',
//     DATABASE_URL = 'DATABASE_URL',

//     PORT = 'PORT',
//     BASE_URL = 'BASE_URL',

//     //BCRYPT
//     BCRYPT_SALT_ROUNDS = 'BCRYPT_SALT_ROUNDS',

//     //Token
//     JWT_ACCESS_SECRET = 'JWT_ACCESS_SECRET',
//     JWT_ACCESS_EXPIRES_IN = 'JWT_ACCESS_EXPIRES_IN',
//     JWT_REFRESH_SECRET = 'JWT_REFRESH_SECRET',
//     JWT_REFRESH_EXPIRES_IN = 'JWT_REFRESH_EXPIRES_IN',


// }
