version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: uillgus_db
    restart: always
    environment:
      - POSTGRES_USER=uillgus
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=uillgus_db
    ports:
      - "5430:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: