# /nginx/nginx.conf

# Set number of worker processes
worker_processes 1;

events {
    worker_connections 1024;
}

http {
    # Define the upstream server block for the NestJS application.
    # The name 'app' must match the service name in docker-compose.pord.yml.
    # Port 9000 is the port the NestJS app listens on inside its container.
    upstream nestjs_app {
        server app:9000;
    }

    server {
        # Nginx will listen on port 80 for incoming HTTP requests.
        listen 80;
        
        # All requests are forwarded to the NestJS application.
        location / {
            # Proxy settings
            proxy_pass http://nestjs_app;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            # WebSocket support (important for NestJS applications that use WebSockets)
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }
    }
}
